[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -p no:warnings"
testpaths = [
    "./tests",
]

[tool.black]
exclude = '''
scripts/.*
'''
line-length = 100
target-version = ['py310']

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 100
multi_line_output = 3
use_parentheses = true
